apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lldap.fullname" . }}-config
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
data:
  config.yaml: |
    # LLDAP Configuration
    listen_addr: "{{ .Values.config.listen_addr }}"
    {{- if .Values.config.web.enabled }}
    web:
      enabled: true
      listen_addr: "{{ .Values.config.web.listen_addr }}"
    {{- else }}
    web:
      enabled: false
    {{- end }}
    database:
      path: "{{ .Values.config.database.path }}"
    domain: "{{ .Values.config.domain }}"
    admin_dn: "{{ .Values.config.admin_dn }}"
    admin_password: "{{ .Values.secret.admin_password }}"
